### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Menkz** [higoka/habbo-downloader#9]
Would be cool to download images such as;
https://images.habbo.com/c_images/web_promo_small/
https://images.habbo.com/c_images/web_promo/
https://images.habbo.com/c_images/targetedoffers/

everything in https://habboo-a.akamaihd.net/c_images/catalogue/
(there's catalog headers - http://images-eussl.habbo.com/c_images/catalogue/val15_cata_header.gif)

**Comment by higoka** [comment]
Okay so `web_promo` and `web_promo_small` should be no problem to implement.
For the `targetedoffers` im not sure i need to look into it.
And for the `catalogue` it's pretty much impossible because you need to know the urls to the images to download them but the problem is there are not defined anywhere as far as i know. Only thing are the catalog icons (icon_1, icon_2, etc) because they just increment the number so its easy to test if the url exists or not.

But anyway i will implement the other things as soon as possible!
Thanks for your suggestions!

**Comment by higoka** [comment]
This has been implemented. 
**For more info see here**: 49d0c1cd4a064eee1b2c05c42baaa04c5226f1e3 655399b75111a432ef791027339bace0d59ba4bf

Thanks again for your suggestions!
